# Generated by Django 3.0.3 on 2020-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200312_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='Wu an  Rose', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Ban chuyên môn', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='studentID',
            field=models.CharField(default='HE1xxxx', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Hà Nội', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Cần cù thì bù siêng năng-Có làm thì mới có ăn', max_length=100),
        ),
    ]
